### ISSUE TITLE
Known SurfStat bugs

### ISSUE THREAD

**Issue by ReinderVosDeWael** [MICA-LAB/BrainStat#24]
Lets keep a list of known SurfStat MATLAB bugs here (and record what fixes we make):

- In SurfStatResels if nargout>1 and slm has a field 'tri' but no field 'resl' it'll error on line 192 because the variable r2 is not defined.

**Comment by sofievalk** [comment]
- [ ] the LinMod function with random effects sometimes breaks (sorry - bad description) I gave Seyma data for this

**Comment by ReinderVosDeWael** [comment]
Can either @sofievalk or @sheyma share this data and associated scripts?

**Comment by sofievalk** [comment]
send
